### PR TITLE
[OOB publish 11/06 @ 10:30 AM PST] Update to inform users that arg() is now also available in advanced hunting

### PR DESCRIPTION
**Pull request by schmurky**

### CODE REVIEW

**Comment by schmurky** [comment]
Hi @guywi-ms this is my first time to request an update. the customer needs to see this ASAP so hopefully i can get it merged soon

**Comment by schmurky** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@schmurky - you should probably reopen this in the private repo so you can get it live without @guywi-ms reviewing and approving. Normally we close PRs in this repo from Microsoft contributors with access to the private repo. That said, I'll keep this open until you've had a chance to open another PR in the private repo. 

If @guywi-ms approves before then, we can just review this one and merge it.

@guywi-ms Can you review the proposed changes? 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by schmurky** [comment]
created this PR https://github.com/MicrosoftDocs/azure-monitor-docs-pr/pull/500 I need this published ASAP so hopefully I can make it to the 3:30 schedule @Jak-MS

**Pull request closed without merging**
