### PR TITLE
Update overview.md

### PR DESCRIPTION
**Pull request by bikbergen**
Microsoft does not support a failover to a different SCOM Managed Instance. this has been confirmed by the Product Group. I think it is important to mention this in the article. contact: Aakash Basavaraj <aakashb@microsoft.com> or Serge Zuidinga <Serge.Zuidinga@microsoft.com>;

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@PriskeyJeronika-MS

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by PriskeyJeronika-MS** [comment]
Hi @ShannonLeavitt, This is taken care in a different PR. Hence, pls close this PR. Thank you!

**Comment by bikbergen** [comment]
Can you let me know in which PR this is taken care of?

For me it would seem logical to have that information available today in the document I requested the change for.

This is an important piece of information when deciding which SCOM product to use.

regards,
Xander
________________________________

**Comment by Jak-MS** [comment]
i see a similar change on the live page now. closing. thanks!

**Pull request closed without merging**
