### PR TITLE
Planned maintenance pages update 100224

### PR DESCRIPTION
**Pull request by MukeshNandaMS**
Updated existing page and added associated image file

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@rboucher - If you accept the proposed changes, the commits will need to be moved to the private repo after the content is ready for publication. If you need help moving the commits, please email the techdocprs team.

@MicrosoftDocs/public-repo-pr-review-team

**Comment by jocalland** [comment]
#sign-off

**Comment by rboucher** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@MukeshNandaMS @rboucher - there are a few issues that need to be addressed before we can merge this PR.

1. the image file name - should consist of only lowercase characters, numbers, and hyphens
2. blurred elements in the image - aren't allowed. you can mask the sensitive data with a white color to "erase" the data.
3. the word impact is inconsistently capitalized in the content. It should only be capitalized if it is part of a feature or product.

please tag me or @MicrosoftDocs/public-repo-pr-review-team when you've corrected these issues and we'll take another look. thanks.

**Comment by Jak-MS** [comment]
#hold-off

**Comment by jocalland** [comment]
Thank you for this feedback Jak.
I will correct this.

Jo

**Comment by jocalland** [comment]
This is my first time working on a PR that someone else created and so I thought it was the one I created earlier today.
So it isn't my document to correct.
So, I learned something today.

**Comment by jocalland** [comment]
#sign-off

**Comment by ShannonLeavitt** [comment]
@MukeshNandaMS - Can you resolve the [issues that are blocking this PR?](https://github.com/MicrosoftDocs/azure-monitor-docs/pull/15#issuecomment-2400881777)

**Comment by jocalland** [comment]
I am the one who worked on fixing the issues and created a new PR to address them. See https://github.com/jocalland/azure-monitor-docs-pr/pull/3.

**Comment by ShannonLeavitt** [comment]
Thanks for the info @jocalland. Now that you have a PR in the private repo, I will close this public PR.

**Pull request closed without merging**
